# ---------------------------------------------------------------------------
#
#       ______                          _      _____
#     |  ____|                        | |    / ____|
#     | |__    __   __   ___   _ __   | |_  | |        ___    _ __    ___
#     |  __|   \ \ / /  / _ \ | '_ \  | __| | |       / _ \  | '__|  / _ \
#     | |____   \ V /  |  __/ | | | | | |_  | |____  | (_) | | |    |  __/
#     |______|   \_/    \___| |_| |_|  \__|  \_____|  \___/  |_|     \___|
#
#         Developed by VertrauterDavid
#
#         https://vertrauterdavid.net/
#         https://github.com/VertrauterDavid/
#
# ---------------------------------------------------------------------------

Settings:
  SpawnLocation: 'world/0/200/0' # Change the setting only with '/event setSpawn'
  MaxBuildHeight: 300 # Maximum build height
  DisableFallDamage: true # Disable fall damage
  DisableItemExplosions: true # Disable item explosions for End Crystal
  HostRank:
    Permission: "event.host" # Permission which is required to receive the host rank upon Join
    JoinCommand: "lp user %player% parent add host"
    QuitCommand: "lp user %player% parent remove host"
  WorldBorder:
    AutoBorder: false # Change the default value of the AutoBorder feature
    DefaultSize: 200 # Default size before and after the event
    DisableEnderPeals: true # Disable EnderPeals outside the world border
    Boost: # Boost players who are outside the border into the border
      Enabled: true
      StrengthXZ: 1.3 # Strength in X and Z direction
      StrengthY: 0.1 # Strength in Y direction
    Damage:
      Buffer: 0.0 # It is recommended to use '0' if the boost is activated
      Amount: 0.2 # Damage per block
  MapReset:
    AutoReset: true # Automatically reset the map after /event stop
    Commands: # Commands that are executed by the console for map reset
      - "/arena reset ARENA extreme" # Example for https://github.com/StrangeOne101/PlatinumArenas
  AutoStop1Player: true # Automatically stop the event if only one player is alive
  AllowItemDropBeforeStart: true # Allow item drop and pickup before the event starts
  DropOnPlayerCount:
    Enabled: true
    Count: 15
  Drop:
    BorderExtra: 3 # Blocks that are dropped in addition to the border size
    CustomCommands: # Commands which are additionally executed after the drop
      - "/kill @e[type=!player]"
  IngameTimer:
    Enabled: true
    Format: "&8» &chh:mm:ss &8«" # Format of the timer - hh = hours, mm = minutes, ss = seconds
  Start:
    CustomCommands: # Commands which are executed on start
      - "/kill @e[type=!player]"
  Stop:
    CustomCommands: # Commands which are executed after the stop
      - "/whitelist on"

Messages:
  Prefix: "&8 | &#559effEvent &8» &7"
  PlayerJoin:
    Enabled: true
    Message: "&a%player% &7joined the Event!"
  PlayerQuit:
    Enabled: true
    Message: "&c%player% &7left the Event!"
  PlayerDeath:
    Enabled: true
    Message1: "&8 | &c☠ &8» &c%player% &7was killed by &c%killer%&7!"
    Message2: "&8 | &c☠ &8» &c%player% &7died!" # Message when the player has simply died and there is no killer!
  StartTimer:
    Timer: 5 # Timer in seconds
    Message: "The game starts in &c%timer% seconds!"
    Title: "%timer%" # 1st row
    SubTitle: "" # 2nd row
    Colors:
      1sec: "&a"
      2sec: "&e"
      3sec: "&6"
      4sec: "&c"
      5sec: "&4"
  Start:
    Message: "&aThe game starts now! Good luck!"
    Title: "&aStart!" # 1st row
    SubTitle: "" # 2nd row
  Stop:
    Enabled: true
    Message: "&cThe game has ended! The winner is %winner%"
    Title: "&c%winner%" # 1st row
    SubTitle: "&7is the winner" # 2nd row
  Actionbar:
    Enabled: true # Overrides the 'IngameTimer' setting
    Message: "&#559effYou are playing the best Event!" # Message that is displayed in the actionbar
  AnnoucementCommand: # %prefix% = Prefix, %message% = Message
    MessageFormat: "%prefix% %message%"
    Title:
      Enabled: true
      Title: "&#559eff&lANNOUNCEMENT" # 1st row
      SubTitle: "&7%message%" # 2nd row

AutoBroadcast: # Messages that are automatically broadcasted
  Enabled: true
  Interval: 60 # Interval in seconds
  Messages:
    - "&7Use &a/buy &7to support us and unlock cool features"
    - "&7You can also join our Discord with &c/discord"
  UseBroadcastCommand: false # Activate whether the 'BroadcastCommand' command should be used
  BroadcastCommand: "/bc %message%"

Kits: # Change the setting only with '/event kit'
  EnabledKit: 'default'
  Kits:
    default: '-'