name: EventCore
version: 1.6
api-version: 1.21
main: net.vertrauterdavid.EventCore
author: VertrauterDavid, JavaMio
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

softdepend: [PlaceholderAPI]

commands:
  announcement:
  eventcore:
  event:
  e:
  kit:
  revive:
  respawn:
  spawn: