name: EventCore
version: 2.0
api-version: 1.21
main: net.vertrauterdavid.EventCore
author: VertrauterDavid, JavaMio
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/
folia-supported: true

softdepend: [PlaceholderAPI]
#depended: [WorldEdit]

commands:
  announcement:
  eventcore:
  event:
  e:
  kit:
  revive:
  respawn:
  spawn: