name: EventCore
version: ${version}
api-version: 1.21
main: me.david.EventCore
author: VertrauterDavid, JavaMio
website: https://github.com/DavidArchive/EventCore
folia-supported: true

softdepend: [PlaceholderAPI]
#depend: [WorldEdit]

#perm
