name: EventCore
version: 1.3
api-version: 1.19
main: net.vertrauterdavid.EventCore
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

softdepend: [PlaceholderAPI]

commands:
  announcement:
  event:
  kit:
  revive: